### ISSUE TITLE
Add Windows and FreeBSD version to Goreleaser

### ISSUE THREAD

**Issue by ross-spencer** [aybabtme/bitflip#1]
There is currently no Windows version for this tool. Goreleaser can be fairly easily updated to include this. I've done something locally to mirror the releases here, and it looks pretty good. I have also included FreeBSD. I am not sure about the interaction with the homebrew components and so these have been commented out. But for reference: 

* https://github.com/ross-spencer/bitflip/commit/9714809ca567126fe5371a98e24691ac7d72d561

NB. It looks like the scripts can be updated to build with Golang 1.15 fairly safely, but after then there is a bit more skew in the Golang updates that cause builds to fail such as indirect includes and other issues around vendoring.

**Comment by aybabtme** [comment]
@ross-spencer sorry I just saw this. If you submit a PR I'll be happy to merge it :)
